name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      # Enable fast test mode (minimal migrations & heavy compute short-circuits) to avoid CI timeouts
      FAST_TESTS: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Contract check
        run: npm run contract
      - name: Version check
        run: npm run version-check
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Tests
        run: npm run test:coverage
      - name: Generate coverage badge
        run: npm run coverage:badge
      - name: Coverage summary
        run: node scripts/coverage-summary.js
      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage/lcov.info
            coverage/coverage-summary.json
            public/coverage-badge.svg
      - name: Validate OpenAPI file exists
        run: |
          test -f openapi.yaml || (echo 'openapi.yaml missing' && exit 1)
      - name: Summarize
        run: echo "CI pipeline completed"

  smoke-preview:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Start preview
        run: |
          npx wrangler dev --local --port=8787 2>&1 | tee wrangler_dev.log &
          echo $! > wrangler_pid
          for i in $(seq 1 20); do
            code=$(curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:8787/health || true)
            if [ "$code" = 200 ]; then echo "Preview up"; break; fi
            sleep 1
            if [ $i -eq 20 ]; then echo 'Preview failed'; cat wrangler_dev.log; exit 1; fi
          done
      - name: Smoke
        env:
          BASE: http://127.0.0.1:8787
        run: |
          chmod +x scripts/smoke.sh
          ./scripts/smoke.sh
      - name: Performance smoke
        env:
          BASE: http://127.0.0.1:8787
          P95_BUDGET_MS: 500
        run: |
          node scripts/perf-smoke.js
      - name: Shutdown
        if: always()
        run: |
          if [ -f wrangler_pid ]; then kill $(cat wrangler_pid) || true; fi